Forum/Forum/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('game_forum/', include('game_forum.urls')),
    path('post_id/', include('game_forum.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('allauth.urls')),


]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Forum/game_forum/urls.py
from django.urls import path
from .views import *


urlpatterns = [
    path('', PostList.as_view(), name='post_list'),
    path('<int:pk>', PostDetail.as_view(), name='post_detail'),
    path('add/', PostCreate.as_view(), name='post_create'),
    path('<int:pk>/edit/', PostUpdate.as_view(), name='post_update'),
    path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
    path('categories/<int:pk>', CategoryListView.as_view(), name='category_list'),
    path('categories/<int:pk>/subscribe', subscribe, name='subscribe'),
    path('', WeeklySendingView.as_view()),
    path('', SendingAboutView.as_view()),


]

Forum/game_forum/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Author(models.Model):
    authorUser = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name="Автор")

    class Meta:
        verbose_name = "Автор"
        verbose_name_plural = "Авторы"

    def __str__(self):
        return self.authorUser.username


class Category(models.Model):
    name = models.CharField('Категория', max_length=64, unique=True, help_text='category name')
    subscribers = models.ManyToManyField(User, related_name='categories')
    description = models.TextField('Описание', default='Описание категории')
    url = models.SlugField(max_length=160, unique=True, default='url категории')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Post(models.Model):
    author = models.ForeignKey(Author, on_delete=models.CASCADE, help_text='user name')
    dateCreation = models.DateTimeField(auto_now_add=True)
    title = models.CharField(max_length=256, help_text='post title')
    text = models.TextField('Тескт')
    rating = models.IntegerField(default=0)
    category = models.ManyToManyField(Category, through='PostCategory')
    is_active = models.BooleanField(default=True)
    content = RichTextUploadingField(blank=True, null=True)

    url = models.SlugField(max_length=130, unique=True, default='url поста')
    image = models.ImageField(upload_to="posts/", default='Изображение')

    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[0:124] + "..."

    def __str__(self):
        return f'{self.title[:20]}'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "Категория поста"
        verbose_name_plural = "категории постов"

    def __str__(self):
        return f'{self.post.title} | {self.category.name}'


class Comment(models.Model):
    commentPost = models.ForeignKey(Post, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    dateCreation = models.DateTimeField(auto_now_add=True)
    text = models.TextField()
    rating = models.IntegerField(default=0)
    content = RichTextUploadingField(blank=True, null=True)

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

Forum/game_forum/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = [
            'title',
            'text',
            'author',
            'category',
            'content',
            'image',

        ]

    def clean(self):
        cleaned_data = super().clean()
        description = cleaned_data.get("title")
        if description is not None and len(description) < 10:
            raise ValidationError({"title": "Заголовк должен быть длиннее"})

        return cleaned_data

    def clean_title(self):
        title = self.cleaned_data["title"]
        if title[0].islower():
            raise ValidationError("Заголовок должен начинаться с заглавной буквы")

        return title

Forum/game_forum/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Group
from django.core.paginator import Paginator
from django.shortcuts import redirect, get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .forms import PostForm
from .models import *
from .filters import PostFilter
from django.views import View
from .tasks import weekly_sending, sending_about
import logging
from django.utils import timezone
import pytz


logger = logging.getLogger(__name__)


class PostList(ListView):
    model = Post
    ordering = '-rating'
    template_name = 'game_forum.html'
    context_object_name = 'game_forum'
    paginate_by = 2

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        current_time = timezone.localtime(timezone.now())
        print(current_time)
        models = Post.objects.all()
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        context['current_time'] = timezone.localtime(timezone.now())
        context['timezones'] = pytz.common_timezones
        return context

    def post(self, request):
        request.session['django_timezone'] = request.POST['timezone']
        return redirect('/game_forum')

    def get_page_context(request):
        post_list = Post.objects.all()
        paginator = Paginator(post_list, 2)
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        return render(request, 'game_forum.html', {'page_obj': page_obj})


class PostDetail(DetailView):
    model = Post
    ordering = 'game_forum'
    template_name = 'post_id.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        current_time = timezone.localtime(timezone.now())
        print(current_time)
        context = super().get_context_data(**kwargs)
        context['current_time'] = timezone.localtime(timezone.now())
        context['timezones'] = pytz.common_timezones
        return context

    def post(self, request):
        request.session['django_timezone'] = request.POST['timezone']
        return redirect('/')


class PostCreate(PermissionRequiredMixin, LoginRequiredMixin, CreateView):
    permission_required = ('game_forum.add_post',)
    raise_exception = True
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'


class PostUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = ('game_forum.update_post',)
    form_class = PostForm
    model = Post
    template_name = 'post_edit.html'


class PostDelete(PermissionRequiredMixin, DeleteView):
    permission_required = ('game_forum.delete_post',)
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('post_list')


@login_required
def update_me(request):
    user = request.user
    premium_group = Group.objects.get()
    if not request.user.groups.filter(name='authors').exists():
        premium_group.user_set.add(user)
    return redirect('game_forum/')


class CategoryListView(ListView):
    model = Post
    template_name = 'category_list.html'
    context_object_name = 'category_game_forum'

    def get_queryset(self):
        self.category = get_object_or_404(Category, id=self.kwargs['pk'])
        queryset = Post.objects.filter(category=self.category).order_by('-dateCreation')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_subscribers'] = self.request.user not in self.category.subscribers.all()
        context['category'] = self.category
        return context


@login_required
def subscribe(request, pk):
    user = request.user
    category = Category.objects.get()
    category.subscribers.add(user)
    message = 'Вы успешно подписались на рассылку новостей из категории'
    return render(request, 'subscribe.html', {'category': category, 'message': message})


class WeeklySendingView(View):
    def get(self, request):
        weekly_sending.delay()
        return redirect('/')


class SendingAboutView(View):
    def get(self, request):
        sending_about.delay()
        return redirect('/')

Forum/game_forum/templates/category_list.html
{% extends 'flatpages/default.html' %}

{% load custom_tags %}

{% block title %}
Форум
{% endblock title %}

{% block content %}
<h1 class="text-center">Форум <span class="text-muted fs-6 fw-normal">Всего: {{ page.obj.paginator.count }}</span></h1>
    {% if is_not_subscribers %}
        <p class="text-center"><a href="{% url 'subscribe' category.id%}" class="btn btn-secondary btn-sm">Подписаться</a></p>
    {% endif %}
<hr>

<ul class="list-group list-group-flush">
    {% for post in category_game_forum%}
        <li class="list-group-item">
            <small class="fw-bold">{{post.dateCreation|date:'d M Y' }}</small>
            <a href="{% url 'post_detail' post.id %}">{{ post.title }}</a>
            <small class="text-muted">(автор: {{ post.author }})</small> <br>
            <small class="fw-bold">категории:
                {% for category in post.category.all %}
                    <a href="{% url 'category_list' category.id%}">{{ category }}</a>
                {% endfor %}
            </small>
            <p>{{post.text | truncatechars:210}}</p>
        </li>
    {% endfor %}
</ul>


{% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1%}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

    {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

Forum/game_forum/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравсвуй! новые статьи за прошедшую неделю!</h2>
<ul>
  {% for post in posts %}
  <li><a href="{{ link }}{{ post.get_absolut_url }}">{{ post.title }}</a></li>
  {% endfor %}
</ul>
</body>
</html>

Forum/game_forum/templates/game_forum.html
{% extends 'flatpages/default.html' %}


{% block title %}
Посты
{% endblock title %}


{% block content %}
   Все Посты
   <form action="" method="get">
       {{ filterset.form.as_p }}
       <input type="submit" value="Найти" />
   </form>
   <hr>
   <h1>{{ an }}</h1>

    {% if perms.game_forum.add_post %}
    <a href="{% url 'post_create' %}">Добавить пост</a>
    {% endif %}

   {% if game_forum %}
       <table>
           <tr>
               <td>Название</td>
               <td>Описание</td>
               <td>Дата написания</td>
               <td>Тема</td>
               <td>Текст</td>
               <td>Медиа</td>
               {% if perms.game_forum.change_post or perms.game_forum.delete_post %}
               <td>Действия</td>
               {% endif %}
           </tr>


           {% for post in game_forum %}
           <tr>
               <td>{{ post.title }}</td>
               <td><div align = "center">{{ post.text|truncatechars:20 }}</div></td>
               <td>{{ post.dateCreation|date:'d M Y' }}</td>
               <td><a class="badge bg-secondary text-decoration-none link-light">{{ category }}</a>
                   {% for category in post.category.all %}
                    <a href="{% url 'category_list' pk=category.id%}">{{ category }}</a>
                    {% endfor %}
               </td>
               <td>{{ post.text}}</td>
               <td><{{post.content}}</td>

               <td>
                   {% if perms.news.change_post %}
                   <a href="{% url 'post_update' pk=post.id %}">Изменить</a>
                   {% endif %}
                   {% if perms.news.delete_post %}
                   <a href="{% url 'post_delete' post.id %}">Удалить</a>
                   {% endif %}

               </td>
           </tr>
           {% endfor %}

       </table>
   {% else %}
       <h2>Постов нет!</h2>
   {% endif %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?Page=1">&laquo; Начало</a>
            <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
        {% endif %}

        <span class="current">
            Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Конец &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock content %}

Forum/game_forum/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Bare - Start Bootstrap Template</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="css/styles.css" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="#">Start Bootstrap</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="#">Home</a></li>
                        <li class="nav-item"><a class="nav-link" href="#">Link</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Dropdown</a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li><hr class="dropdown-divider" /></li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Page content-->
        <div class="container">
            <div class="text-center mt-5">
                <h1>A Bootstrap 5 Starter Template</h1>
                <p class="lead">A complete project boilerplate built with Bootstrap</p>
                <p>Bootstrap v5.1.3</p>
            </div>
        </div>
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
    </body>
</html>

Forum/game_forum/templates/post_created_mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравствуй! Новый <a href="{{ link }}">пост</a> в твоём любимом разделе!</h2>
<p>{{ text }}</p>
</body>
</html>

Forum/game_forum/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление поста</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ post.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

Forum/game_forum/templates/post_edit.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Пост</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

Forum/game_forum/templates/post_id.html
{% extends 'flatpages/default.html' %}

{% load custom_tags %}

{% block title %}
Post
{% endblock title %}

{% block content %}
<h1>{{ post }}</h1>
<h1>{{post.dateCreation}}</h1>
<h1>{{post.text }}</h1>
<h1>{{post.rating}}</h1>
<h1>{{post.content}}</h1>

{% endblock content %}

Forum/game_forum/templates/subscribe.html
{% extends 'flatpages/default.html' %}

{% block content%}
    <h1 class="text-center">{{ message }} {{ category }}!</h1>
{% endblock content%}